apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql01-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      volumes:
        - name: mysql-pv-storage
          persistentVolumeClaim:
            claimName: mysql01-pv-claim
      containers:
      - name: mysql
        image: mysql
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - liveness.sh
          initialDelaySeconds: 60
          periodSeconds: 2
        ports:
        - containerPort: 3306
        volumeMounts:
          - mountPath: "/var/lib/mysql"
            name: mysql-pv-storage

---

apiVersion: v1
kind: Service
metadata:
  name: mysql-service
spec:
  selector:
    app: mysql
  type: ClusterIP
  ports:
  - port: 3306
    targetPort: 3306