apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps
        imagePullPolicy: Never
        livenessProbe:
          exec:
            command:
            - sh
            - liveness.sh
          initialDelaySeconds: 60
          periodSeconds: 2
        ports:
        - name: ftp
          containerPort: 21
        - name: min
          containerPort: 31110
        - name: max
          containerPort: 31111

---

apiVersion: v1
kind: Service
metadata:
  name: ftps-service
  annotations:
    metallb.universe.tf/allow-shared-ip: shared
spec:
  selector:
    app: ftps
  type: LoadBalancer
  ports:
  - name: port
    port: 21
    targetPort: 21
  - name: min
    port: 31110
    targetPort: 31110
  - name: max
    port: 31111
    targetPort: 31111
